---
title: "Analysis of Cross-Partisan Interaction in course name"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(ggplot2)
library(reshape2)
library(htmlTable)
##########################################

loadOrSourceFiles <- function(path, pattern = NULL,ignore.case = FALSE, load = TRUE ){
  files <- list.files(path = path,pattern = pattern,ignore.case = ignore.case)
  for( file in files){
    file_full <- paste0(path,file)
    if(load == TRUE ) {
      load(file_full, envir = globalenv())
    } else {
      source(file_full)
    }
  }
}

loadOrSourceFiles(path = "./data/cleaned/", pattern = "_hks\\.RData")
loadOrSourceFiles(path = "./functions/", load = FALSE)
users <- users_hks
upvotes <- upvotes_hks
posts <- posts_hks
plot.title <- "American Government"
```

Column {.tabset}
-----------------------------------------------------------------------
### **Demographics of course participants**

```{r }
# source: https://cran.r-project.org/web/packages/htmlTable/vignettes/tables.html
output <- data.frame( course_enroll = c("5,409", "49.8%", "79.9%", "32 (14.2)", "", "", "14.3%") ,
                      survey_resp = c("2,009", "57.7%","83.3%","36 (14.5)","52.9%","57.2%","31.8%"),
                      usa_samp =c("1,340","61.0%","86.2%","38 (14.9)","57.7%","56.0%","32.7%"),
                      any_act= c("569","59.4%","88.1%","40 (15.1)","63.4%","75.4%","61.0%")
                      )
htmlTable(output,
          header = c("Course Enrollment", "Survey Response", 
                     "USA Sample", "Any Forum Activity"), 
          n.tspanner = c(1, 4 ,2), 
          rnames = c( "Observations",
                      "% Female",
                      "College Degree",
                      "Median Age (SD)",
                      "% Teachers",
                      "Intended  Course Completion",
                      "Actual Course Completion"
          ) ,
          tspanner = c("","","")
             #caption="Basic table with both column spanners (groups) and row groups",
        )
```

### **Ideology and forum activity in substantive course threads**

```{r ,fig.height = 8}
makeActivityIdeologyGraph(plot.data = users)
```


Column
-----------------------------------------------------------------------

### **Distribution of upvotes per reply in substantive course threads**

```{r}
makeUpvoteFacetGraph(plot.data = upvotes)

```

### **Distribution of comments per reply in substantive course threads**

```{r}
makeCommentFacetGraph(plot.data = posts)
```

